# Generated by Django 6.0.7 on 2026-08-05 01:41

import django.core.validators
import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[student_app.validators.validate_name_format])),
                ('student_email', models.EmailField(max_length=200, unique=True, validators=[student_app.validators.validate_school_email])),
                ('personal_email', models.EmailField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('locker_number', models.IntegerField(default=110, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200), student_app.validators.validate_locker_number])),
                ('locker_combination', models.CharField(default='12-12-12', max_length=20, validators=[student_app.validators.validate_combination_format])),
                ('good_student', models.BooleanField(default=True)),
                ('subjects', models.ManyToManyField(related_name='students', to='subject_app.subject')),
            ],
        ),
    ]
