# Generated by Django 6.0.7 on 2026-07-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=200)),
                ('personal_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('locker_number', models.IntegerField(max_length=4)),
                ('locker_combination', models.CharField(max_length=20)),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
