# Generated by Django 6.0.7 on 2026-07-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_locker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='good_student',
        ),
        migrations.AddField(
            model_name='student',
            name='on_team',
            field=models.BooleanField(default=False),
        ),
    ]
