# Generated by Django 6.0.7 on 2026-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_remove_student_good_student_student_on_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
