# Generated by Django 6.0.7 on 2026-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(default=True),
        ),
    ]
