# Generated by Django 6.0.7 on 2026-07-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_personal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='on_team',
        ),
    ]
