# Generated by Django 6.0.7 on 2026-08-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
    ]
